// Copyright (c) 2020-2025 Zhang Jingcheng <diogin@gmail.com>.
// All rights reserved.
// Use of this source code is governed by a BSD-style license that can be found in the LICENSE file.

// HTTP/2 types and protocol elements. See RFC 9113 and RFC 7541.

// Server Push is not supported because it's rarely used. Chrome and Firefox even removed it.

package hemi

import (
	"bytes"
	"encoding/binary"
	"io"
	"net"
	"sync"
	"sync/atomic"
	"syscall"
	"time"
)

// http2Conn
type http2Conn interface {
	// Imports
	httpConn
	// Methods
}

// http2Conn_ is a parent.
type http2Conn_[S http2Stream] struct { // for backend2Conn and server2Conn
	// Parent
	httpConn_
	// Conn states (stocks)
	// Conn states (controlled)
	outFrame http2OutFrame[S] // used by c.manage() itself to send special out frames. immediately reset after use
	// Conn states (non-zeros)
	netConn      net.Conn                         // *net.TCPConn, *tls.Conn, *net.UnixConn
	rawConn      syscall.RawConn                  // for syscall. only usable when netConn is TCP/UDS
	peerSettings http2Settings                    // settings of the remote peer
	freeSlots    [http2MaxConcurrentStreams]uint8 // a stack holding free slots for streams of this connection in c.activeStreams and c.activeStreamIDs
	freeSlotsTop uint8                            // the stack top of c.freeSlots
	inBuffer     *http2Buffer                     // http2Buffer in use, for receiving incoming frames. may be replaced again and again during connection's lifetime
	decodeTable  hpackTable                       // <= 5 KiB. hpack table used for decoding field blocks that are received from remote
	incomingChan chan any                         // frames and errors generated by c.receive() and waiting for c.manage() to consume
	localWindow  int32                            // connection-level window (buffer) size for receiving incoming DATA frames
	remoteWindow int32                            // connection-level window (buffer) size for sending outgoing DATA frames
	outgoingChan chan *http2OutFrame[S]           // frames generated by streams of this connection and waiting for c.manage() to send
	encodeTable  hpackTable                       // <= 5 KiB. hpack table used for encoding field lists that are sent to remote
	// Conn states (zeros)
	lastWrite        time.Time                    // deadline of last write operation
	lastRead         time.Time                    // deadline of last read operation
	activeStreams    [http2MaxConcurrentStreams]S // <= 1 KiB. active (http2StateOpen, http2StateLocalClosed, http2StateRemoteClosed) streams
	lastSettingsTime time.Time                    // last settings time
	lastPingTime     time.Time                    // last ping time
	inFrame0         http2InFrame                 // incoming frame 0
	inFrame1         http2InFrame                 // incoming frame 1
	inFrame          *http2InFrame                // current incoming frame. refers to inFrame0 or inFrame1 in turn
	vector           net.Buffers                  // used by writev in c.manage()
	fixedVector      [64][]byte                   // 1.5 KiB. used by writev in c.manage()
	_http2Conn0                                   // all values in this struct must be zero by default!
}
type _http2Conn0 struct { // for fast reset, entirely
	activeStreamIDs    [http2MaxConcurrentStreams + 1]uint32 // ids of c.activeStreams. the extra 1 id is used for fast linear searching
	readDeadlines      [http2MaxConcurrentStreams + 1]int64  // 1 KiB
	writeDeadlines     [http2MaxConcurrentStreams + 1]int64  // 1 KiB
	_                  uint32
	lastStreamID       uint32 // id of last stream sent to backend or received by server
	cumulativeInFrames int64  // num of incoming frames
	concurrentStreams  uint8  // num of active streams
	acknowledged       bool   // server settings acknowledged by client?
	pingSent           bool   // is there a ping frame sent and waiting for response?
	inBufferEdge       uint16 // incoming data ends at c.inBuffer.buf[c.inBufferEdge]
	sectBack           uint16 // incoming frame section (header or payload) begins from c.inBuffer.buf[c.sectBack]
	sectFore           uint16 // incoming frame section (header or payload) ends at c.inBuffer.buf[c.sectFore]
	contBack           uint16 // incoming continuation part (header or payload) begins from c.inBuffer.buf[c.contBack]
	contFore           uint16 // incoming continuation part (header or payload) ends at c.inBuffer.buf[c.contFore]
}

func (c *http2Conn_[S]) onGet(id int64, holder holder, netConn net.Conn, rawConn syscall.RawConn) {
	c.httpConn_.onGet(id, holder)

	c.netConn = netConn
	c.rawConn = rawConn
	c.peerSettings = http2InitialSettings
	c.freeSlots = http2FreeSlots
	c.freeSlotsTop = 255 // +1 becomes 0
	if c.inBuffer == nil {
		c.inBuffer = getHTTP2Buffer()
		c.inBuffer.incRef()
	}
	c.decodeTable.init()
	if c.incomingChan == nil {
		c.incomingChan = make(chan any)
	}
	c.localWindow = _2G1 - _64K1                      // as a receiver, we disable connection-level flow control
	c.remoteWindow = c.peerSettings.initialWindowSize // after we received the peer's preface, this value will be changed to the real value.
	if c.outgoingChan == nil {
		c.outgoingChan = make(chan *http2OutFrame[S])
	}
	c.encodeTable.init()
}
func (c *http2Conn_[S]) onPut() {
	c.netConn = nil
	c.rawConn = nil
	// c.inBuffer is reserved
	// c.decodeTable is reserved
	// c.incomingChan is reserved
	// c.outgoingChan is reserved
	// c.encodeTable is reserved
	c.lastWrite = time.Time{}
	c.lastRead = time.Time{}
	c.activeStreams = [http2MaxConcurrentStreams]S{}
	c.lastSettingsTime = time.Time{}
	c.lastPingTime = time.Time{}
	c.inFrame0.zero()
	c.inFrame1.zero()
	c.inFrame = nil
	c.vector = nil
	c.fixedVector = [64][]byte{}
	c._http2Conn0 = _http2Conn0{}

	c.httpConn_.onPut()
}

func (c *http2Conn_[S]) receive(asServer bool) { // runner, employed by c.manage()
	if DebugLevel() >= 1 {
		defer Printf("conn=%d c.receive() quit\n", c.id)
	}
	if asServer { // We must read the HTTP/2 PRISM at the very begining
		if err := c.setReadDeadline(); err != nil {
			c.incomingChan <- err
			return
		}
		if err := c._growInFrame(24); err != nil { // HTTP/2 PRISM is exactly 24 bytes
			c.incomingChan <- err
			return
		}
		if !bytes.Equal(c.inBuffer.buf[:24], backend2PrefaceAndMore[:24]) {
			c.incomingChan <- http2ErrorProtocol
			return
		}
		c.incomingChan <- nil // notify c.manage() that we have successfully read the HTTP/2 PRISM
	}
	for { // each incoming frame
		inFrame, err := c.recvInFrame()
		if err != nil {
			c.incomingChan <- err
			return
		}
		if inFrame.kind == http2FrameGoaway {
			c.incomingChan <- http2ErrorNoError
			return
		}
		c.incomingChan <- inFrame
	}
}

func (c *http2Conn_[S]) _getFreeSlot() uint8 {
	c.freeSlotsTop++
	return c.freeSlots[c.freeSlotsTop]
}
func (c *http2Conn_[S]) _putFreeSlot(slot uint8) {
	c.freeSlots[c.freeSlotsTop] = slot
	c.freeSlotsTop--
}

func (c *http2Conn_[S]) appendStream(stream S) { // O(1)
	slot := c._getFreeSlot()
	stream.setSlot(slot)
	c.activeStreams[slot] = stream
	c.activeStreamIDs[slot] = stream.nativeID()
	if DebugLevel() >= 2 {
		Printf("conn=%d appendStream=%d at %d\n", c.id, stream.nativeID(), slot)
	}
}
func (c *http2Conn_[S]) searchStream(streamID uint32) S { // O(http2MaxConcurrentStreams), but in practice this linear search algorithm should be fast enough
	c.activeStreamIDs[http2MaxConcurrentStreams] = streamID // the stream id to search for
	slot := uint8(0)
	for c.activeStreamIDs[slot] != streamID {
		slot++
	}
	if slot != http2MaxConcurrentStreams { // found
		if DebugLevel() >= 2 {
			Printf("conn=%d searchStream=%d at %d\n", c.id, streamID, slot)
		}
		return c.activeStreams[slot]
	} else { // not found
		var null S // nil
		return null
	}
}
func (c *http2Conn_[S]) retireStream(stream S) { // O(1)
	slot := stream.getSlot()
	if DebugLevel() >= 2 {
		Printf("conn=%d retireStream=%d at %d\n", c.id, stream.nativeID(), slot)
	}
	var null S // nil
	c.activeStreams[slot] = null
	c.activeStreamIDs[slot] = 0
	c._putFreeSlot(slot)
}

func (c *http2Conn_[S]) recvInFrame() (*http2InFrame, error) { // excluding pushPromise, which is not supported, and continuation, which cannot arrive alone
	// Receive frame header
	c.sectBack = c.sectFore
	if err := c.setReadDeadline(); err != nil {
		return nil, err
	}
	if err := c._growInFrame(9); err != nil {
		return nil, err
	}
	// Decode frame header
	if c.inFrame == nil || c.inFrame == &c.inFrame1 {
		c.inFrame = &c.inFrame0
	} else {
		c.inFrame = &c.inFrame1
	}
	inFrame := c.inFrame
	if err := inFrame.decodeHeader(c.inBuffer.buf[c.sectBack:c.sectFore]); err != nil {
		return nil, err
	}
	// Receive frame payload
	c.sectBack = c.sectFore
	if err := c._growInFrame(inFrame.length); err != nil {
		return nil, err
	}
	// Mark frame payload
	inFrame.inBuffer = c.inBuffer
	inFrame.efctFrom = c.sectBack
	inFrame.efctEdge = c.sectFore
	if !inFrame.isUnknown() {
		// Check the frame
		if err := http2InFrameCheckers[inFrame.kind](inFrame); err != nil {
			return nil, err
		}
	}
	c.cumulativeInFrames++
	if c.cumulativeInFrames == 10 && !c.acknowledged { // TODO: change this policy?
		return nil, http2ErrorSettingsTimeout
	}
	if inFrame.kind == http2FrameFields && !inFrame.endFields { // continuations follow, coalesce them into fields frame
		if err := c._coalesceContinuations(inFrame); err != nil {
			return nil, err
		}
	}
	if DebugLevel() >= 2 {
		Printf("conn=%d <--- %+v\n", c.id, inFrame)
	}
	return inFrame, nil
}
func (c *http2Conn_[S]) _growInFrame(size uint16) error {
	c.sectFore += size // size is limited, so won't overflow
	if c.sectFore <= c.inBufferEdge {
		return nil
	}
	// c.sectFore > c.inBufferEdge, needs grow.
	if c.sectFore > c.inBuffer.size() { // needs slide
		if c.inBuffer.getRef() == 1 { // no streams are referring to c.inBuffer, so just slide
			c.inBufferEdge = uint16(copy(c.inBuffer.buf[:], c.inBuffer.buf[c.sectBack:c.inBufferEdge]))
		} else { // there are remaining streams referring to c.inBuffer. use a new inBuffer
			oldBuffer := c.inBuffer
			c.inBuffer = getHTTP2Buffer()
			c.inBuffer.incRef()
			c.inBufferEdge = uint16(copy(c.inBuffer.buf[:], oldBuffer.buf[c.sectBack:c.inBufferEdge]))
			oldBuffer.decRef()
		}
		c.sectFore -= c.sectBack
		c.sectBack = 0
	}
	return c._fillInBuffer(c.sectFore - c.inBufferEdge)
}
func (c *http2Conn_[S]) _fillInBuffer(size uint16) error {
	n, err := c.readAtLeast(c.inBuffer.buf[c.inBufferEdge:], int(size))
	if DebugLevel() >= 2 {
		Printf("--------------------- conn=%d CALL READ=%d -----------------------\n", c.id, n)
	}
	if err != nil && DebugLevel() >= 2 {
		Printf("conn=%d error=%s\n", c.id, err.Error())
	}
	c.inBufferEdge += uint16(n)
	return err
}

func (c *http2Conn_[S]) _coalesceContinuations(fieldsInFrame *http2InFrame) error { // into a single fields frame
	fieldsInFrame.inBuffer = nil // unset temporarily, will be restored at the end of continuations
	var continuationInFrame http2InFrame
	c.contBack, c.contFore = c.sectFore, c.sectFore
	for i := 0; i < 4; i++ { // max 4 continuation frames are allowed!
		// Receive continuation header
		if err := c._growContinuationFrame(9, fieldsInFrame); err != nil {
			return err
		}
		// Decode continuation header
		if err := continuationInFrame.decodeHeader(c.inBuffer.buf[c.contBack:c.contFore]); err != nil {
			return err
		}
		// Check continuation header
		if continuationInFrame.length == 0 || fieldsInFrame.length+continuationInFrame.length > http2MaxFrameSize {
			return http2ErrorFrameSize
		}
		if continuationInFrame.streamID != fieldsInFrame.streamID || continuationInFrame.kind != http2FrameContinuation {
			return http2ErrorProtocol
		}
		// Receive continuation payload
		c.contBack = c.contFore
		if err := c._growContinuationFrame(continuationInFrame.length, fieldsInFrame); err != nil {
			return err
		}
		// Append continuation frame to fields frame
		copy(c.inBuffer.buf[fieldsInFrame.efctEdge:], c.inBuffer.buf[c.contBack:c.contFore]) // may overwrite padding if exists
		fieldsInFrame.efctEdge += continuationInFrame.length
		fieldsInFrame.length += continuationInFrame.length // we don't care if padding is overwritten. just accumulate
		c.sectFore += continuationInFrame.length           // also accumulate fields payload, with padding included
		// End of fields frame?
		if continuationInFrame.endFields {
			fieldsInFrame.endFields = true
			fieldsInFrame.inBuffer = c.inBuffer // restore the inBuffer
			c.sectFore = c.contFore             // for next frame.
			return nil
		}
		c.contBack = c.contFore
	}
	return http2ErrorEnhanceYourCalm
}
func (c *http2Conn_[S]) _growContinuationFrame(size uint16, fieldsInFrame *http2InFrame) error {
	c.contFore += size                // won't overflow
	if c.contFore <= c.inBufferEdge { // inBuffer is sufficient
		return nil
	}
	// Needs grow. Cases are (A is payload of the fields frame):
	// c.inBuffer: [| .. ] | A | 9 | B | 9 | C | 9 | D |
	// c.inBuffer: [| .. ] | AB | oooo | 9 | C | 9 | D |
	// c.inBuffer: [| .. ] | ABC | ooooooooooo | 9 | D |
	// c.inBuffer: [| .. ] | ABCD | oooooooooooooooooo |
	if c.contFore > c.inBuffer.size() { // needs slide
		if c.sectBack == 0 { // cannot slide again
			// This should only happens when looking for frame header, the 9 bytes
			return http2ErrorFrameSize
		}
		// Now slide. Skip holes (if any) when sliding
		inBuffer := c.inBuffer
		if c.inBuffer.getRef() != 1 { // there are still streams referring to c.inBuffer. use a new inBuffer
			c.inBuffer = getHTTP2Buffer()
			c.inBuffer.incRef()
		}
		c.sectFore = uint16(copy(c.inBuffer.buf[:], inBuffer.buf[c.sectBack:c.sectFore]))
		c.inBufferEdge = c.sectFore + uint16(copy(c.inBuffer.buf[c.sectFore:], inBuffer.buf[c.contBack:c.inBufferEdge]))
		if inBuffer != c.inBuffer {
			inBuffer.decRef()
		}
		fieldsInFrame.efctFrom -= c.sectBack
		fieldsInFrame.efctEdge -= c.sectBack
		c.sectBack = 0
		c.contBack = c.sectFore
		c.contFore = c.contBack + size
	}
	return c._fillInBuffer(c.contFore - c.inBufferEdge)
}

func (c *http2Conn_[S]) processDataInFrame(dataInFrame *http2InFrame) error {
	// TODO
	return nil
}
func (c *http2Conn_[S]) processPriorityInFrame(priorityInFrame *http2InFrame) error { return nil } // do nothing, priority frames are ignored
func (c *http2Conn_[S]) processResetStreamInFrame(resetStreamInFrame *http2InFrame) error {
	streamID := resetStreamInFrame.streamID
	if streamID > c.lastStreamID {
		// RST_STREAM frames MUST NOT be sent for a stream in the "idle" state. If a RST_STREAM frame identifying an idle stream is received,
		// the recipient MUST treat this as a connection error (Section 5.4.1) of type PROTOCOL_ERROR.
		return http2ErrorProtocol
	}
	// TODO
	return nil
}
func (c *http2Conn_[S]) processPushPromiseInFrame(pushPromiseInFrame *http2InFrame) error {
	panic("pushPromise frames should be rejected priorly")
}
func (c *http2Conn_[S]) processPingInFrame(pingInFrame *http2InFrame) error {
	if pingInFrame.ack { // pong
		if !c.pingSent { // TODO: confirm this
			return http2ErrorProtocol
		}
		return nil
	}
	if now := time.Now(); c.lastPingTime.IsZero() || now.Sub(c.lastPingTime) >= time.Second {
		c.lastPingTime = now
	} else {
		return http2ErrorEnhanceYourCalm
	}
	pongOutFrame := &c.outFrame
	pongOutFrame.streamID = 0
	pongOutFrame.length = 8
	pongOutFrame.kind = http2FramePing
	pongOutFrame.ack = true
	pongOutFrame.payload = pingInFrame.effective()
	err := c.sendOutFrame(pongOutFrame)
	pongOutFrame.zero()
	return err
}
func (c *http2Conn_[S]) processGoawayInFrame(goawayInFrame *http2InFrame) error {
	panic("goaway frames should be hijacked by c.receive()")
}
func (c *http2Conn_[S]) processWindowUpdateInFrame(windowUpdateInFrame *http2InFrame) error {
	windowSize := binary.BigEndian.Uint32(windowUpdateInFrame.effective())
	if windowSize == 0 || windowSize > _2G1 {
		// The legal range for the increment to the flow-control window is 1 to 2^31 - 1 (2,147,483,647) octets.
		return http2ErrorProtocol
	}
	// TODO
	c.localWindow = int32(windowSize)
	Printf("conn=%d stream=%d windowUpdate=%d\n", c.id, windowUpdateInFrame.streamID, windowSize)
	return nil
}
func (c *http2Conn_[S]) processContinuationInFrame(continuationInFrame *http2InFrame) error {
	panic("lonely continuation frames should be rejected priorly")
}

func (c *http2Conn_[S]) _updatePeerSettings(settingsInFrame *http2InFrame, asClient bool) error {
	settings := settingsInFrame.effective()
	windowDelta := int32(0)
	for i, j, n := uint16(0), uint16(0), settingsInFrame.length/6; i < n; i++ {
		ident := binary.BigEndian.Uint16(settings[j : j+2])
		value := binary.BigEndian.Uint32(settings[j+2 : j+6])
		switch ident {
		case http2SettingMaxHeaderTableSize:
			c.peerSettings.maxHeaderTableSize = value
			// TODO: immediate Dynamic Table Size Update
		case http2SettingEnablePush:
			if value > 1 || (value == 1 && asClient) {
				return http2ErrorProtocol
			}
			c.peerSettings.enablePush = false // we don't support server push
		case http2SettingMaxConcurrentStreams:
			c.peerSettings.maxConcurrentStreams = value
			// TODO: notify shrink
		case http2SettingInitialWindowSize:
			if value > _2G1 {
				return http2ErrorFlowControl
			}
			windowDelta = int32(value) - c.peerSettings.initialWindowSize
		case http2SettingMaxFrameSize:
			if value < _16K || value > _16M-1 {
				return http2ErrorProtocol
			}
			c.peerSettings.maxFrameSize = value // we don't use this. we only send frames of the minimal size
		case http2SettingMaxHeaderListSize:
			c.peerSettings.maxHeaderListSize = value // this is only an advisory.
		default:
			// RFC 9113 (section 6.5.2): An endpoint that receives a SETTINGS frame with any unknown or unsupported identifier MUST ignore that setting.
		}
		j += 6
	}
	if windowDelta != 0 {
		c.peerSettings.initialWindowSize += windowDelta
		//c._adjustStreamWindows(windowDelta)
	}
	Printf("conn=%d peerSettings=%+v\n", c.id, c.peerSettings)
	return nil
}

func (c *http2Conn_[S]) decodeFields(fields []byte, input *[]byte) bool {
	// TODO
	return false
	/*
		var fieldName, lineValue []byte
		var (
			I  uint32 // the decoded integer
			j  int    // index of fields
			ok bool   // decode succeeds or not
		)
		i, n := 0, len(fields)
		for i < n {
			b := fields[i]
			if b >= 0b_1000_0000 { // 6.1. Indexed Header Field Representation
				I, j, ok = hpackDecodeVarint(fields[i:], 7, http2MaxTableIndex)
				if !ok || I == 0 { // The index value of 0 is not used.  It MUST be treated as a decoding error if found in an indexed header field representation.
					Println("decode error")
					return false
				}
				fieldName, lineValue, ok = c.decodeTable.get(I)
				if !ok { // Indices strictly greater than the sum of the lengths of both tables MUST be treated as a decoding error.
					return false
				}
				i += j
			} else if b >= 0b_0010_0000 && b < 0b_0100_0000 { // 6.3. Dynamic Table Size Update
				I, j, ok = hpackDecodeVarint(fields[i:], 5, http2MaxTableSize)
				if !ok {
					Println("decode error")
					return false
				}
				i += j
				Printf("update size=%d\n", I)
			} else { // 0b_01xx_xxxx, 0b_0000_xxxx, 0b_0001_xxxx
				var N int
				if b >= 0b_0100_0000 { // 6.2.1. Literal Header Field with Incremental Indexing
					N = 6
				} else { // 0b_0000_xxxx (6.2.2. Literal Header Field without Indexing), 0b_0001_xxxx (6.2.3. Literal Header Field Never Indexed)
					N = 4
				}
				I, j, ok = hpackDecodeVarint(fields[i:], N, http2MaxTableIndex)
				if !ok {
					println("decode error")
					return false
				}
				i += j
				if I != 0 { // Indexed Name
					fieldName, _, ok = c.decodeTable.get(I)
					if !ok {
						Println("decode error")
						return false
					}
				} else { // New Name
					fieldName, j, ok = hpackDecodeString(input, fields[i:], 255)
					if !ok || len(fieldName) == 0 {
						Println("decode error")
						return false
					}
					i += j
				}
				lineValue, j, ok = hpackDecodeString(input, fields[i:], _16K)
				if !ok {
					Println("decode error")
					return false
				}
				i += j
				if b >= 0b_0100_0000 {
					c.decodeTable.add(fieldName, lineValue)
				} else if b >= 0b_0001_0000 {
					// TODO: never indexed
				}
			}
			Printf("name=%s value=%s\n", fieldName, lineValue)
		}
		return i == n
	*/
}

func (c *http2Conn_[S]) sendOutFrame(outFrame *http2OutFrame[S]) error {
	outHeader := outFrame.encodeHeader()
	if len(outFrame.payload) > 0 {
		c.vector = c.fixedVector[0:2]
		c.vector[1] = outFrame.payload
	} else {
		c.vector = c.fixedVector[0:1]
	}
	c.vector[0] = outHeader
	if err := c.setWriteDeadline(); err != nil {
		return err
	}
	n, err := c.writev(&c.vector)
	if DebugLevel() >= 2 {
		Printf("--------------------- conn=%d CALL WRITE=%d -----------------------\n", c.id, n)
		Printf("conn=%d ---> %+v\n", c.id, outFrame)
	}
	return err
}

func (c *http2Conn_[S]) encodeFields(fields []byte, output *[]byte) {
	// TODO
	// uses c.encodeTable
}

func (c *http2Conn_[S]) remoteAddr() net.Addr { return c.netConn.RemoteAddr() }

func (c *http2Conn_[S]) setReadDeadline() error {
	if deadline := time.Now().Add(c.readTimeout); deadline.Sub(c.lastRead) >= time.Second {
		if err := c.netConn.SetReadDeadline(deadline); err != nil {
			return err
		}
		c.lastRead = deadline
	}
	return nil
}
func (c *http2Conn_[S]) setWriteDeadline() error {
	if deadline := time.Now().Add(c.writeTimeout); deadline.Sub(c.lastWrite) >= time.Second {
		if err := c.netConn.SetWriteDeadline(deadline); err != nil {
			return err
		}
		c.lastWrite = deadline
	}
	return nil
}

func (c *http2Conn_[S]) readAtLeast(dst []byte, min int) (int, error) {
	return io.ReadAtLeast(c.netConn, dst, min)
}
func (c *http2Conn_[S]) write(src []byte) (int, error) { return c.netConn.Write(src) }
func (c *http2Conn_[S]) writev(srcVec *net.Buffers) (int64, error) {
	return srcVec.WriteTo(c.netConn)
}

// http2Stream
type http2Stream interface {
	// Imports
	httpStream
	// Methods
	nativeID() uint32   // http/2 native stream id
	getSlot() uint8     // at activeStreamIDs and activeStreams
	setSlot(slot uint8) // at activeStreamIDs and activeStreams
}

// http2Stream_ is a parent.
type http2Stream_[C http2Conn] struct { // for backend2Stream and server2Stream
	// Parent
	httpStream_[C]
	// Stream states (stocks)
	// Stream states (controlled)
	// Stream states (non-zeros)
	id           uint32 // the stream id. we use 4 byte instead of int64 (which is used in http/3) to save memory space! see activeStreamIDs
	localWindow  int32  // stream-level window (buffer) size for receiving incoming DATA frames
	remoteWindow int32  // stream-level window (buffer) size for sending outgoing DATA frames
	// Stream states (zeros)
	_http2Stream0 // all values in this struct must be zero by default!
}
type _http2Stream0 struct { // for fast reset, entirely
	slot  uint8 // the slot at s.conn.activeStreamIDs and s.conn.activeStreams
	state uint8 // http2StateOpen, http2StateLocalClosed, http2StateRemoteClosed
}

func (s *http2Stream_[C]) onUse(conn C, id uint32) {
	s.httpStream_.onUse(conn)

	s.id = id
}
func (s *http2Stream_[C]) onEnd() {
	s._http2Stream0 = _http2Stream0{}

	s.httpStream_.onEnd()
}

func (s *http2Stream_[C]) nativeID() uint32   { return s.id }
func (s *http2Stream_[C]) getSlot() uint8     { return s.slot }
func (s *http2Stream_[C]) setSlot(slot uint8) { s.slot = slot }

func (s *http2Stream_[C]) ID() int64 { return int64(s.id) } // implements httpStream interface

func (s *http2Stream_[C]) markBroken()    { s.conn.markBroken() }      // TODO: limit the breakage in the stream?
func (s *http2Stream_[C]) isBroken() bool { return s.conn.isBroken() } // TODO: limit the breakage in the stream?

func (s *http2Stream_[C]) setReadDeadline() error { // for content and trailers i/o only
	// TODO
	return nil
}
func (s *http2Stream_[C]) setWriteDeadline() error {
	// TODO
	return nil
}

func (s *http2Stream_[C]) read(dst []byte) (int, error) { // for content and trailers i/o only
	// TODO
	return 0, nil
}
func (s *http2Stream_[C]) readFull(dst []byte) (int, error) { // for content and trailers i/o only
	// TODO
	return 0, nil
}
func (s *http2Stream_[C]) write(src []byte) (int, error) {
	// TODO
	return 0, nil
}
func (s *http2Stream_[C]) writev(srcVec *net.Buffers) (int64, error) {
	// TODO
	return 0, nil
}

// _http2In_ is a mixin.
type _http2In_ struct { // for backend2Response and server2Request
	// Parent
	*_httpIn_
	// Stream states (stocks)
	// Stream states (controlled)
	// Stream states (non-zeros)
	// Stream states (zeros)
}

func (r *_http2In_) onUse(parent *_httpIn_) {
	r._httpIn_ = parent
}
func (r *_http2In_) onEnd() {
	r._httpIn_ = nil
}

func (r *_http2In_) _growHeaders(size int32) bool {
	edge := r.inputEdge + size      // size is ensured to not overflow
	if edge < int32(cap(r.input)) { // fast path
		return true
	}
	if edge > _16K { // exceeds the max header section limit
		return false
	}
	input := GetNK(int64(edge)) // 4K/16K
	copy(input, r.input[0:r.inputEdge])
	if cap(r.input) != cap(r.stockInput) {
		PutNK(r.input)
	}
	r.input = input
	return true
}

func (r *_http2In_) readContent() (data []byte, err error) {
	// TODO
	return
}
func (r *_http2In_) _readSizedContent() ([]byte, error) {
	// r.stream.setReadDeadline() // may be called multiple times during the reception of the sized content
	return nil, nil
}
func (r *_http2In_) _readVagueContent() ([]byte, error) {
	// r.stream.setReadDeadline() // may be called multiple times during the reception of the vague content
	return nil, nil
}

// _http2Out_ is a mixin.
type _http2Out_ struct { // for backend2Request and server2Response
	// Parent
	*_httpOut_
	// Stream states (stocks)
	// Stream states (controlled)
	// Stream states (non-zeros)
	// Stream states (zeros)
}

func (r *_http2Out_) onUse(parent *_httpOut_) {
	r._httpOut_ = parent
}
func (r *_http2Out_) onEnd() {
	r._httpOut_ = nil
}

func (r *_http2Out_) addHeader(name []byte, value []byte) bool {
	// TODO
	return false
}
func (r *_http2Out_) header(name []byte) (value []byte, ok bool) {
	// TODO
	return
}
func (r *_http2Out_) hasHeader(name []byte) bool {
	// TODO
	return false
}
func (r *_http2Out_) delHeader(name []byte) (deleted bool) {
	// TODO
	return false
}
func (r *_http2Out_) delHeaderAt(i uint8) {
	// TODO
}

func (r *_http2Out_) sendChain() error {
	// TODO
	return nil
}
func (r *_http2Out_) _sendEntireChain() error {
	// TODO
	return nil
}
func (r *_http2Out_) _sendSingleRange() error {
	// TODO
	return nil
}
func (r *_http2Out_) _sendMultiRanges() error {
	// TODO
	return nil
}

func (r *_http2Out_) echoChain() error {
	// TODO
	return nil
}

func (r *_http2Out_) addTrailer(name []byte, value []byte) bool {
	// TODO
	return false
}
func (r *_http2Out_) trailer(name []byte) (value []byte, ok bool) {
	// TODO
	return
}
func (r *_http2Out_) trailers() []byte {
	// TODO
	return nil
}

func (r *_http2Out_) proxyPassBytes(data []byte) error { return r.writeBytes(data) }

func (r *_http2Out_) finalizeVague2() error {
	// TODO
	if r.numTrailerFields == 1 { // no trailer section
	} else { // with trailer section
	}
	return nil
}

func (r *_http2Out_) writeHeaders() error { // used by echo and pass
	// TODO
	r.outputEdge = 0 // now that header fields are all sent, r.output will be used by trailer fields (if any), so reset it.
	return nil
}
func (r *_http2Out_) writePiece(piece *Piece, vague bool) error {
	// TODO
	return nil
}
func (r *_http2Out_) _writeTextPiece(piece *Piece) error {
	// TODO
	return nil
}
func (r *_http2Out_) _writeFilePiece(piece *Piece) error {
	// TODO
	// r.stream.setWriteDeadline() // for _writeFilePiece
	// r.stream.write() or r.stream.writev()
	return nil
}
func (r *_http2Out_) writeVector() error {
	// TODO
	// r.stream.setWriteDeadline() // for writeVector
	// r.stream.writev()
	return nil
}
func (r *_http2Out_) writeBytes(data []byte) error {
	// TODO
	// r.stream.setWriteDeadline() // for writeBytes
	// r.stream.write()
	return nil
}

// _http2Socket_ is a mixin.
type _http2Socket_ struct { // for backend2Socket and server2Socket
	// Parent
	*_httpSocket_
	// Stream states (stocks)
	// Stream states (controlled)
	// Stream states (non-zeros)
	// Stream states (zeros)
}

func (s *_http2Socket_) onUse(parent *_httpSocket_) {
	s._httpSocket_ = parent
}
func (s *_http2Socket_) onEnd() {
	s._httpSocket_ = nil
}

func (s *_http2Socket_) todo2() {
	s.todo()
}

const ( // HTTP/2 sizes and limits for both of our HTTP/2 server and HTTP/2 backend
	http2MaxFrameSize         = _16K // currently hardcoded. must <= _64K1 - 9
	http2MaxTableSize         = _4K  // currently hardcoded
	http2MaxConcurrentStreams = 127  // currently hardcoded
)

const ( // HTTP/2 frame kinds
	http2FrameData         = 0x0
	http2FrameFields       = 0x1 // a.k.a. headers
	http2FramePriority     = 0x2 // deprecated. ignored on receiving, and we won't send
	http2FrameResetStream  = 0x3 // a.k.a. rst_stream
	http2FrameSettings     = 0x4
	http2FramePushPromise  = 0x5 // not supported
	http2FramePing         = 0x6
	http2FrameGoaway       = 0x7
	http2FrameWindowUpdate = 0x8
	http2FrameContinuation = 0x9
	http2NumFrameKinds     = 10
)

const ( // HTTP/2 stream states. Server Push related states are not supported
	http2StateIdle         = 0 // must be 0, default value
	http2StateOpen         = 1
	http2StateRemoteClosed = 2
	http2StateLocalClosed  = 3
	http2StateClosed       = 4
)

const ( // HTTP/2 settings
	http2SettingMaxHeaderTableSize   = 0x1
	http2SettingEnablePush           = 0x2
	http2SettingMaxConcurrentStreams = 0x3
	http2SettingInitialWindowSize    = 0x4
	http2SettingMaxFrameSize         = 0x5
	http2SettingMaxHeaderListSize    = 0x6
)

// http2Settings
type http2Settings struct {
	maxHeaderTableSize   uint32 // 0x1
	enablePush           bool   // 0x2, always false as we don't support server push
	maxConcurrentStreams uint32 // 0x3
	initialWindowSize    int32  // 0x4
	maxFrameSize         uint32 // 0x5
	maxHeaderListSize    uint32 // 0x6
}

var http2InitialSettings = http2Settings{ // default settings for both backend2Conn and server2Conn
	maxHeaderTableSize:   _4K,   // the table size that we allow the remote peer to use
	enablePush:           false, // we don't support server push
	maxConcurrentStreams: 127,   // the number that we allow the remote peer to initiate
	initialWindowSize:    _64K1, // this requires the size of content buffer must up to 64K1
	maxFrameSize:         _16K,  // the size that we allow the remote peer to use
	maxHeaderListSize:    _16K,  // the size that we allow the remote peer to use
}

const ( // HTTP/2 error codes
	http2CodeNoError            = 0x0 // The associated condition is not a result of an error. For example, a GOAWAY might include this code to indicate graceful shutdown of a connection.
	http2CodeProtocol           = 0x1 // The endpoint detected an unspecific protocol error. This error is for use when a more specific error code is not available.
	http2CodeInternal           = 0x2 // The endpoint encountered an unexpected internal error.
	http2CodeFlowControl        = 0x3 // The endpoint detected that its peer violated the flow-control protocol.
	http2CodeSettingsTimeout    = 0x4 // The endpoint sent a SETTINGS frame but did not receive a response in a timely manner. See Section 6.5.3 ("Settings Synchronization").
	http2CodeStreamClosed       = 0x5 // The endpoint received a frame after a stream was half-closed.
	http2CodeFrameSize          = 0x6 // The endpoint received a frame with an invalid size.
	http2CodeRefusedStream      = 0x7 // The endpoint refused the stream prior to performing any application processing (see Section 8.7 for details).
	http2CodeCancel             = 0x8 // The endpoint uses this error code to indicate that the stream is no longer needed.
	http2CodeCompression        = 0x9 // The endpoint is unable to maintain the field section compression context for the connection.
	http2CodeConnect            = 0xa // The connection established in response to a CONNECT request (Section 8.5) was reset or abnormally closed.
	http2CodeEnhanceYourCalm    = 0xb // The endpoint detected that its peer is exhibiting a behavior that might be generating excessive load.
	http2CodeInadequateSecurity = 0xc // The underlying transport has properties that do not meet minimum security requirements (see Section 9.2).
	http2CodeHTTP11Required     = 0xd // The endpoint requires that HTTP/1.1 be used instead of HTTP/2.
	http2NumErrorCodes          = 14  // Unknown or unsupported error codes MUST NOT trigger any special behavior. These MAY be treated by an implementation as being equivalent to INTERNAL_ERROR.
)

// http2Error denotes both connection error and stream error.
type http2Error uint32

var ( // HTTP/2 errors
	http2ErrorNoError            http2Error = http2CodeNoError
	http2ErrorProtocol           http2Error = http2CodeProtocol
	http2ErrorInternal           http2Error = http2CodeInternal
	http2ErrorFlowControl        http2Error = http2CodeFlowControl
	http2ErrorSettingsTimeout    http2Error = http2CodeSettingsTimeout
	http2ErrorStreamClosed       http2Error = http2CodeStreamClosed
	http2ErrorFrameSize          http2Error = http2CodeFrameSize
	http2ErrorRefusedStream      http2Error = http2CodeRefusedStream
	http2ErrorCancel             http2Error = http2CodeCancel
	http2ErrorCompression        http2Error = http2CodeCompression
	http2ErrorConnect            http2Error = http2CodeConnect
	http2ErrorEnhanceYourCalm    http2Error = http2CodeEnhanceYourCalm
	http2ErrorInadequateSecurity http2Error = http2CodeInadequateSecurity
	http2ErrorHTTP11Required     http2Error = http2CodeHTTP11Required
)

func (e http2Error) Error() string {
	if e < http2NumErrorCodes {
		return http2CodeTexts[e]
	}
	return "UNKNOWN_ERROR"
}

var http2CodeTexts = [...]string{
	http2CodeNoError:            "NO_ERROR",
	http2CodeProtocol:           "PROTOCOL_ERROR",
	http2CodeInternal:           "INTERNAL_ERROR",
	http2CodeFlowControl:        "FLOW_CONTROL_ERROR",
	http2CodeSettingsTimeout:    "SETTINGS_TIMEOUT",
	http2CodeStreamClosed:       "STREAM_CLOSED",
	http2CodeFrameSize:          "FRAME_SIZE_ERROR",
	http2CodeRefusedStream:      "REFUSED_STREAM",
	http2CodeCancel:             "CANCEL",
	http2CodeCompression:        "COMPRESSION_ERROR",
	http2CodeConnect:            "CONNECT_ERROR",
	http2CodeEnhanceYourCalm:    "ENHANCE_YOUR_CALM",
	http2CodeInadequateSecurity: "INADEQUATE_SECURITY",
	http2CodeHTTP11Required:     "HTTP_1_1_REQUIRED",
}

func hpackDecodeVarint(fields []byte, N int, max uint32) (I uint32, j int, ok bool) { // ok = false if fields is malformed or result > max
	// Pseudocode to decode an integer I is as follows:
	//
	// decode I from the next N bits
	// if I < 2^N - 1, return I
	// else
	//     M = 0
	//     repeat
	//         B = next octet
	//         I = I + (B & 127) * 2^M
	//         M = M + 7
	//     while B & 128 == 128
	//     return I
	l := len(fields)
	if l == 0 {
		return 0, 0, false
	}
	K := uint32(1<<N) - 1
	I = uint32(fields[0]) & K
	if I < K {
		return I, 1, I <= max
	}
	j = 1
	for M := 0; j < l; M += 7 { // M -> 7,14,21,28
		B := fields[j]
		j++
		I += uint32(B&0x7F) << M // M = 0,7,14,21,28
		if I > max {
			break
		}
		if B < 0x80 {
			return I, j, true
		}
	}
	return I, j, false
}
func hpackDecodeString(input []byte, fields []byte, max uint32) (i int, j int, ok bool) { // ok = false if fields is malformed or length of result string > max
	I, j, ok := hpackDecodeVarint(fields, 7, max)
	if !ok {
		return 0, j, false
	}
	H := fields[0] >= 0x80
	fields = fields[j:]
	if I > uint32(len(fields)) {
		return 0, j, false
	}
	j += int(I)
	if H { // the string is huffman encoded, needs decoding
		i, ok := httpHuffmanDecode(input, fields[:I])
		return i, j, ok
	}
	copy(input, fields[:I])
	return j, j, true
}

func hpackEncodeVarint(fields []byte, I uint32, N int) (int, bool) { // ok = false if fields is not large enough
	// Pseudocode to encode an integer I is as follows:
	//
	// if I < 2^N - 1, encode I on N bits
	// else
	//     encode (2^N - 1) on N bits
	//     I = I - (2^N - 1)
	//     while I >= 128
	//          encode (I % 128 + 128) on 8 bits
	//          I = I / 128
	//     encode I on 8 bits
	l := len(fields)
	if l == 0 {
		return 0, false
	}
	K := uint32(1<<N) - 1
	if I < K {
		fields[0] = byte(I)
		return 1, true
	}
	fields[0] = byte(K)
	j := 1
	for I -= K; I >= 0x80 && j < l; I /= 0x80 {
		fields[j] = byte(I) | 0x80
		j++
	}
	if j == l {
		return j, false
	}
	fields[j] = byte(I)
	return j + 1, true
}
func hpackEncodeString(fields []byte, output []byte) (int, bool) { // ok = false if fields is not large enough
	I := len(output)
	if I == 0 {
		return 0, true
	}
	n := httpHuffmanLength(output)
	H := n < I
	if !H {
		n = I
	}
	j, ok := hpackEncodeVarint(fields, uint32(n), 7)
	if !ok {
		return j, false
	}
	if H {
		fields[0] |= 0x80
	}
	fields = fields[j:]
	if len(fields) < n {
		return j, false
	}
	if H {
		httpHuffmanEncode(fields, output)
	} else {
		copy(fields, output)
	}
	return j + n, true
}

// hpackTableEntry is an HPACK table entry.
type hpackTableEntry struct { // 8 bytes
	nameHash  uint16 // name hash
	nameFrom  uint16 // name edge at nameFrom+nameSize
	nameSize  uint8  // must <= 255
	isStatic  bool   // ...
	valueEdge uint16 // value: [nameFrom+nameSize:valueEdge]
}

var hpackStaticBytes = []byte(":authority:methodGET:methodPOST:path/:path/index.html:schemehttp:schemehttps:status200:status204:status206:status304:status400:status404:status500accept-charsetaccept-encodinggzip, deflateaccept-languageaccept-rangesacceptaccess-control-allow-originageallowauthorizationcache-controlcontent-dispositioncontent-encodingcontent-languagecontent-lengthcontent-locationcontent-rangecontent-typecookiedateetagexpectexpiresfromhostif-matchif-modified-sinceif-none-matchif-rangeif-unmodified-sincelast-modifiedlinklocationmax-forwardsproxy-authenticateproxy-authorizationrangerefererrefreshretry-afterserverset-cookiestrict-transport-securitytransfer-encodinguser-agentvaryviawww-authenticate")

// hpackStaticTable is the HPACK static table.
var hpackStaticTable = [...]hpackTableEntry{
	0:  {0, 0, 0, true, 0},         // empty, never used
	1:  {1059, 0, 10, true, 10},    // :authority=
	2:  {699, 10, 7, true, 20},     // :method=GET
	3:  {699, 20, 7, true, 31},     // :method=POST
	4:  {487, 31, 5, true, 37},     // :path=/
	5:  {487, 37, 5, true, 53},     // :path=/index.html
	6:  {687, 53, 7, true, 64},     // :scheme=http
	7:  {687, 64, 7, true, 76},     // :scheme=https
	8:  {734, 76, 7, true, 86},     // :status=200
	9:  {734, 86, 7, true, 96},     // :status=204
	10: {734, 96, 7, true, 106},    // :status=206
	11: {734, 106, 7, true, 116},   // :status=304
	12: {734, 116, 7, true, 126},   // :status=400
	13: {734, 126, 7, true, 136},   // :status=404
	14: {734, 136, 7, true, 146},   // :status=500
	15: {1415, 146, 14, true, 160}, // accept-charset=
	16: {1508, 160, 15, true, 188}, // accept-encoding=gzip, deflate
	17: {1505, 188, 15, true, 203}, // accept-language=
	18: {1309, 203, 13, true, 216}, // accept-ranges=
	19: {624, 216, 6, true, 222},   // accept=
	20: {2721, 222, 27, true, 249}, // access-control-allow-origin=
	21: {301, 249, 3, true, 252},   // age=
	22: {543, 252, 5, true, 257},   // allow=
	23: {1425, 257, 13, true, 270}, // authorization=
	24: {1314, 270, 13, true, 283}, // cache-control=
	25: {2013, 283, 19, true, 302}, // content-disposition=
	26: {1647, 302, 16, true, 318}, // content-encoding=
	27: {1644, 318, 16, true, 334}, // content-language=
	28: {1450, 334, 14, true, 348}, // content-length=
	29: {1665, 348, 16, true, 364}, // content-location=
	30: {1333, 364, 13, true, 377}, // content-range=
	31: {1258, 377, 12, true, 389}, // content-type=
	32: {634, 389, 6, true, 395},   // cookie=
	33: {414, 395, 4, true, 399},   // date=
	34: {417, 399, 4, true, 403},   // etag=
	35: {649, 403, 6, true, 409},   // expect=
	36: {768, 409, 7, true, 416},   // expires=
	37: {436, 416, 4, true, 420},   // from=
	38: {446, 420, 4, true, 424},   // host=
	39: {777, 424, 8, true, 432},   // if-match=
	40: {1660, 432, 17, true, 449}, // if-modified-since=
	41: {1254, 449, 13, true, 462}, // if-none-match=
	42: {777, 462, 8, true, 470},   // if-range=
	43: {1887, 470, 19, true, 489}, // if-unmodified-since=
	44: {1314, 489, 13, true, 502}, // last-modified=
	45: {430, 502, 4, true, 506},   // link=
	46: {857, 506, 8, true, 514},   // location=
	47: {1243, 514, 12, true, 526}, // max-forwards=
	48: {1902, 526, 18, true, 544}, // proxy-authenticate=
	49: {2048, 544, 19, true, 563}, // proxy-authorization=
	50: {525, 563, 5, true, 568},   // range=
	51: {747, 568, 7, true, 575},   // referer=
	52: {751, 575, 7, true, 582},   // refresh=
	53: {1141, 582, 11, true, 593}, // retry-after=
	54: {663, 593, 6, true, 599},   // server=
	55: {1011, 599, 10, true, 609}, // set-cookie=
	56: {2648, 609, 25, true, 634}, // strict-transport-security=
	57: {1753, 634, 17, true, 651}, // transfer-encoding=
	58: {1019, 651, 10, true, 661}, // user-agent=
	59: {450, 661, 4, true, 665},   // vary=
	60: {320, 665, 3, true, 668},   // via=
	61: {1681, 668, 16, true, 684}, // www-authenticate=
}

const hpackMaxTableIndex = 61 + 124 // static[1-61] + dynamic[62-185]

// hpackTable
type hpackTable struct { // <= 5KiB
	tableSize  uint32                       // <= http2MaxTableSize
	freeSize   uint32                       // <= tableSize
	iNewest    uint32                       // append to t.entries[t.iNewest]
	iOldest    uint32                       // evict from t.entries[t.iOldest]
	numEntries uint32                       // num of current entries
	maxEntries uint32                       // cap(entries). max num = floor(http2MaxTableSize/(1+32)) = 124, where 1 is the size of a shortest field
	entries    [124]hpackTableEntry         // implemented as a circular buffer: https://en.wikipedia.org/wiki/Circular_buffer
	content    [http2MaxTableSize - 32]byte // the content buffer. http2MaxTableSize-32 is the upper limit size that the remote encoder can occupy
}

func (t *hpackTable) init() {
	t.tableSize = http2MaxTableSize
	t.freeSize = t.tableSize
	t.iNewest = 0
	t.iOldest = 0
	t.numEntries = 0
	t.maxEntries = uint32(cap(t.entries))
}

func (t *hpackTable) add(name []byte, value []byte) bool { // name is not empty. sizes of name and value are limited
	if t.numEntries == t.maxEntries { // too many entries
		return false
	}
	nameSize, valueSize := uint32(len(name)), uint32(len(value))
	entrySize := nameSize + valueSize + 32 // won't overflow
	// Before a new entry is added to the dynamic table, entries are evicted
	// from the end of the dynamic table until the size of the dynamic table
	// is less than or equal to (maximum size - new entry size) or until the
	// table is empty.
	//
	// If the size of the new entry is less than or equal to the maximum
	// size, that entry is added to the table.  It is not an error to
	// attempt to add an entry that is larger than the maximum size; an
	// attempt to add an entry larger than the maximum size causes the table
	// to be emptied of all existing entries and results in an empty table.
	if entrySize > t.tableSize {
		t.freeSize = t.tableSize
		t.numEntries = 0
		t.iOldest = t.iNewest
		return true
	}
	for t.freeSize < entrySize {
		t._evictOne()
	}
	t.freeSize -= entrySize
	var newEntry hpackTableEntry
	if t.numEntries > 0 {
		newEntry.nameFrom = t.entries[t.iNewest].valueEdge
		if t.iNewest++; t.iNewest == t.maxEntries {
			t.iNewest = 0 // wrap around
		}
	} else { // empty table. starts from 0
		newEntry.nameFrom = 0
	}
	newEntry.nameSize = uint8(nameSize)
	nameEdge := newEntry.nameFrom + uint16(newEntry.nameSize)
	newEntry.valueEdge = nameEdge + uint16(valueSize)
	copy(t.content[newEntry.nameFrom:nameEdge], name)
	if valueSize > 0 {
		copy(t.content[nameEdge:newEntry.valueEdge], value)
	}
	t.numEntries++
	t.entries[t.iNewest] = newEntry
	return true
}
func (t *hpackTable) get(index uint32) (name []byte, value []byte, ok bool) {
	if index >= t.numEntries {
		return nil, nil, false
	}
	if t.iNewest <= t.iOldest && index > t.iNewest {
		index -= t.iNewest
		index = t.maxEntries - index
	} else {
		index = t.iNewest - index
	}
	entry := t.entries[index]
	nameEdge := entry.nameFrom + uint16(entry.nameSize)
	return t.content[entry.nameFrom:nameEdge], t.content[nameEdge:entry.valueEdge], true
}
func (t *hpackTable) resize(newMaxSize uint32) { // newMaxSize must <= http2MaxTableSize
	if newMaxSize > http2MaxTableSize {
		BugExitln("newMaxSize out of range")
	}
	if newMaxSize >= t.tableSize {
		t.freeSize += newMaxSize - t.tableSize
	} else {
		for usedSize := t.tableSize - t.freeSize; usedSize > newMaxSize; usedSize = t.tableSize - t.freeSize {
			t._evictOne()
		}
		t.freeSize -= t.tableSize - newMaxSize
	}
	t.tableSize = newMaxSize
}
func (t *hpackTable) _evictOne() {
	if t.numEntries == 0 {
		BugExitln("no entries to evict!")
	}
	evictee := &t.entries[t.iOldest]
	t.freeSize += uint32(evictee.valueEdge - evictee.nameFrom + 32)
	if t.iOldest++; t.iOldest == t.maxEntries {
		t.iOldest = 0
	}
	if t.numEntries--; t.numEntries == 0 {
		t.iNewest = t.iOldest
	}
}

var http2FreeSlots = [http2MaxConcurrentStreams]uint8{
	0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16,
	17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32,
	33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
	49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
	65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80,
	81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96,
	97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
	113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126,
}

// http2Buffer is the HTTP/2 incoming buffer.
type http2Buffer struct {
	buf [9 + http2MaxFrameSize]byte // frame header + frame payload
	ref atomic.Int32
}

var poolHTTP2Buffer sync.Pool

func getHTTP2Buffer() *http2Buffer {
	var inBuffer *http2Buffer
	if x := poolHTTP2Buffer.Get(); x == nil {
		inBuffer = new(http2Buffer)
	} else {
		inBuffer = x.(*http2Buffer)
	}
	return inBuffer
}
func putHTTP2Buffer(inBuffer *http2Buffer) { poolHTTP2Buffer.Put(inBuffer) }

func (b *http2Buffer) size() uint16  { return uint16(cap(b.buf)) }
func (b *http2Buffer) getRef() int32 { return b.ref.Load() }
func (b *http2Buffer) incRef()       { b.ref.Add(1) }
func (b *http2Buffer) decRef() {
	if b.ref.Add(-1) == 0 {
		if DebugLevel() >= 1 {
			Printf("putHTTP2Buffer ref=%d\n", b.ref.Load())
		}
		putHTTP2Buffer(b)
	}
}

// http2InFrame is the HTTP/2 incoming frame.
type http2InFrame struct { // 24 bytes
	inBuffer  *http2Buffer // the inBuffer that holds payload
	streamID  uint32       // the real type is uint31
	length    uint16       // length of payload. the real type is uint24, but we never allow sizes out of range of uint16, so use uint16
	kind      uint8        // see http2FrameXXX
	endFields bool         // is END_FIELDS flag set?
	endStream bool         // is END_STREAM flag set?
	ack       bool         // is ACK flag set?
	padded    bool         // is PADDED flag set?
	priority  bool         // is PRIORITY flag set?
	efctFrom  uint16       // (effective) payload from
	efctEdge  uint16       // (effective) payload edge
}

func (f *http2InFrame) zero() { *f = http2InFrame{} }

func (f *http2InFrame) decodeHeader(inHeader []byte) error {
	inHeader[5] &= 0x7f // ignore the reserved bit
	f.streamID = binary.BigEndian.Uint32(inHeader[5:9])
	if f.streamID != 0 && f.streamID&1 == 0 { // we don't support server push, so only odd stream ids are allowed
		return http2ErrorProtocol
	}
	length := uint32(inHeader[0])<<16 | uint32(inHeader[1])<<8 | uint32(inHeader[2])
	if length > http2MaxFrameSize {
		// An endpoint MUST send an error code of FRAME_SIZE_ERROR if a frame exceeds the size defined in SETTINGS_MAX_FRAME_SIZE,
		// exceeds any limit defined for the frame type, or is too small to contain mandatory frame data.
		return http2ErrorFrameSize
	}
	f.length = uint16(length)
	f.kind = inHeader[3]
	flags := inHeader[4]
	f.endFields = flags&0x04 != 0 && (f.kind == http2FrameFields || f.kind == http2FrameContinuation)
	f.endStream = flags&0x01 != 0 && (f.kind == http2FrameData || f.kind == http2FrameFields)
	f.ack = flags&0x01 != 0 && (f.kind == http2FrameSettings || f.kind == http2FramePing)
	f.padded = flags&0x08 != 0 && (f.kind == http2FrameData || f.kind == http2FrameFields)
	f.priority = flags&0x20 != 0 && f.kind == http2FrameFields
	return nil
}

func (f *http2InFrame) isUnknown() bool   { return f.kind >= http2NumFrameKinds }
func (f *http2InFrame) effective() []byte { return f.inBuffer.buf[f.efctFrom:f.efctEdge] } // effective payload

var http2InFrameCheckers = [http2NumFrameKinds]func(*http2InFrame) error{ // for known frames
	(*http2InFrame).checkAsData,
	(*http2InFrame).checkAsFields,
	(*http2InFrame).checkAsPriority,
	(*http2InFrame).checkAsResetStream,
	(*http2InFrame).checkAsSettings,
	(*http2InFrame).checkAsPushPromise,
	(*http2InFrame).checkAsPing,
	(*http2InFrame).checkAsGoaway,
	(*http2InFrame).checkAsWindowUpdate,
	(*http2InFrame).checkAsContinuation,
}

func (f *http2InFrame) checkAsData() error {
	var minLength uint16 = 0 // Data (..)
	if f.padded {
		minLength += 1 // Pad Length (8)
	}
	if f.length < minLength {
		return http2ErrorFrameSize
	}
	if f.streamID == 0 {
		return http2ErrorProtocol
	}
	var padLength, othersLen uint16 = 0, 0
	if f.padded {
		padLength = uint16(f.inBuffer.buf[f.efctFrom])
		othersLen += 1
		f.efctFrom += 1
	}
	if padLength > 0 { // drop padding
		if othersLen+padLength >= f.length {
			return http2ErrorProtocol
		}
		f.efctEdge -= padLength
	}
	return nil
}
func (f *http2InFrame) checkAsFields() error {
	var minLength uint16 = 1 // Field Block Fragment
	if f.padded {
		minLength += 1 // Pad Length (8)
	}
	if f.priority {
		minLength += 5 // Exclusive (1) + Stream Dependency (31) + Weight (8)
	}
	if f.length < minLength {
		return http2ErrorFrameSize
	}
	if f.streamID == 0 {
		return http2ErrorProtocol
	}
	var padLength, othersLen uint16 = 0, 0
	if f.padded { // skip pad length byte
		padLength = uint16(f.inBuffer.buf[f.efctFrom])
		othersLen += 1
		f.efctFrom += 1
	}
	if f.priority { // skip stream dependency and weight
		othersLen += 5
		f.efctFrom += 5
	}
	if padLength > 0 { // drop padding
		if othersLen+padLength >= f.length {
			return http2ErrorProtocol
		}
		f.efctEdge -= padLength
	}
	return nil
}
func (f *http2InFrame) checkAsPriority() error {
	if f.length != 5 {
		return http2ErrorFrameSize
	}
	if f.streamID == 0 {
		return http2ErrorProtocol
	}
	return nil
}
func (f *http2InFrame) checkAsResetStream() error {
	if f.length != 4 {
		return http2ErrorFrameSize
	}
	if f.streamID == 0 {
		return http2ErrorProtocol
	}
	return nil
}
func (f *http2InFrame) checkAsSettings() error {
	if f.length%6 != 0 || f.length > 48 { // we allow 8 defined settings.
		return http2ErrorFrameSize
	}
	if f.streamID != 0 {
		return http2ErrorProtocol
	}
	if f.ack && f.length != 0 {
		return http2ErrorFrameSize
	}
	return nil
}
func (f *http2InFrame) checkAsPushPromise() error {
	return http2ErrorProtocol // we don't support server push
}
func (f *http2InFrame) checkAsPing() error {
	if f.length != 8 {
		return http2ErrorFrameSize
	}
	if f.streamID != 0 {
		return http2ErrorProtocol
	}
	return nil
}
func (f *http2InFrame) checkAsGoaway() error {
	if f.length < 8 {
		return http2ErrorFrameSize
	}
	if f.streamID != 0 {
		return http2ErrorProtocol
	}
	return nil
}
func (f *http2InFrame) checkAsWindowUpdate() error {
	if f.length != 4 {
		return http2ErrorFrameSize
	}
	return nil
}
func (f *http2InFrame) checkAsContinuation() error {
	return http2ErrorProtocol // continuation frames cannot be alone. we coalesce continuation frames on receiving fields frame
}

// http2OutFrame is the HTTP/2 outgoing frame.
type http2OutFrame[S http2Stream] struct { // 64 bytes
	streamID  uint32   // id of stream, duplicate for convenience
	length    uint16   // length of payload. the real type is uint24, but we never use sizes out of range of uint16, so use uint16
	kind      uint8    // see http2FrameXXX. WARNING: http2FramePushPromise and http2FrameContinuation are NOT allowed! we don't use them.
	endFields bool     // is END_FIELDS flag set?
	endStream bool     // is END_STREAM flag set?
	ack       bool     // is ACK flag set?
	padded    bool     // is PADDED flag set?
	header    [9]byte  // frame header is encoded here
	outBuffer [12]byte // small payload of the frame is placed here temporarily
	payload   []byte   // refers to the payload
	stream    S        // the http/2 stream to which the frame belongs. nil if the frame belongs to conneciton
}

func (f *http2OutFrame[S]) zero() { *f = http2OutFrame[S]{} }

func (f *http2OutFrame[S]) encodeHeader() (outHeader []byte) { // caller must ensure the frame is legal.
	if f.streamID > 0x7fffffff {
		BugExitln("stream id too large")
	}
	if f.length > http2MaxFrameSize {
		BugExitln("frame length too large")
	}
	if f.kind == http2FramePushPromise || f.kind == http2FrameContinuation {
		BugExitln("push promise and continuation are not allowed as out frame")
	}
	outHeader = f.header[:]
	outHeader[0], outHeader[1], outHeader[2] = byte(f.length>>16), byte(f.length>>8), byte(f.length)
	outHeader[3] = f.kind
	flags := uint8(0x00)
	if f.endFields && f.kind == http2FrameFields { // we never use http2FrameContinuation
		flags |= 0x04
	}
	if f.endStream && (f.kind == http2FrameData || f.kind == http2FrameFields) {
		flags |= 0x01
	}
	if f.ack && (f.kind == http2FrameSettings || f.kind == http2FramePing) {
		flags |= 0x01
	}
	if f.padded && (f.kind == http2FrameData || f.kind == http2FrameFields) {
		flags |= 0x08
	}
	outHeader[4] = flags
	binary.BigEndian.PutUint32(outHeader[5:9], f.streamID)
	return
}
